node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/xjr100419/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('discovery-service') {
                sh "docker login 192.168.80.180:5000 -u admin -p 123456"
                def app = docker.build "192.168.80.180:5000/demo/discovery-service:${env.version}"
                app.push()
            }
        }



        stage ('Final') {
            build job: 'account-service-pipeline', wait: false
        }

    }

}